version: '3.8'

services:
  # Servicio de Aplicaci√≥n PHP + Apache
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chilechilito_web
    restart: always
    ports:
      - "${WEB_PORT}"  # Acceder en http://localhost:8080
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - APP_URL=${APP_URL}
      - TZ=${TZ}
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Permite acceder al MySQL del host
